### ISSUE TITLE
Special error occur on Rails5.2.0 only.

### ISSUE THREAD

**Issue by raykin** [raykin/rails_dictionary#1]
```
From: /Users/raykin/studio/rails_dictionary/lib/rails_dictionary/models/acts_as_dict_slave.rb @ line 81 Student#city_name=:

    71: define_method(method_name) do |value, options={}|
    72:   options.merge!(name_en: value)
    73:   dict_type_id = DictType.revert("#{self.class.table_name.singularize}_#{colname}")
    74:   options.merge!(dict_type_id: dict_type_id)
    75:   exist_dictionary = Dictionary.where(options)
    76:   binding.pry
    77:   if exist_dictionary.present?
    78:     exist_id = exist_dictionary.first.id
    79:   else
    80:     binding.pry
 => 81:     exist_id = send("create_#{belongs_to_name}!", options).id
    82:   end
    83:   send "#{colname}=", exist_id
    84: end

[1] pry(#<Student>)> c
F

Failures:

  1) RailsDictionary Student create a student with new city
     Failure/Error: exist_id = send("create_#{belongs_to_name}!", options).id

     ActiveRecord::RecordNotSaved:
       You cannot call create unless the parent is saved
     # ./lib/rails_dictionary/models/acts_as_dict_slave.rb:81:in `block in dict_name_equal'
     # ./spec/rails_dictionary_spec.rb:115:in `block (3 levels) in <top (required)>'

Finished in 39.49 seconds (files took 1.49 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/rails_dictionary_spec.rb:112 # RailsDictionary Student create a student with new city

~/studio/rails_dictionary (b2.0 ✘)✹✭ ᐅ
```

**Comment by raykin** [comment]
This error only happened on Rails 5.2.0.  5.2.1 is ok.

**Comment by raykin** [comment]
Maybe Rails consider it's a bug of itself.
